security:
    encoders:
        GemeenteAmsterdam\FixxxSchuldhulp\Entity\Gebruiker:
            algorithm: bcrypt
    providers:
        database:
            entity:
                class: GemeenteAmsterdam\FixxxSchuldhulp\Entity\Gebruiker
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        app:
            pattern: ^/app
            security: true
            provider: database
            anonymous: true
            form_login:
                login_path: gemeenteamsterdam_fixxxschuldhulp_appsecurity_login
                check_path: gemeenteamsterdam_fixxxschuldhulp_appsecurity_login
            logout:
                path: /app/logout
                target: /
        main:
            anonymous: true
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
