framework:
  workflows:
    dossier_flow:
      type: state_machine
      marking_store:
        type: single_state
        arguments:
          - status
      supports:
        - GemeenteAmsterdam\FixxxSchuldhulp\Entity\Dossier
      places:
        - bezig_madi
        - compleet_madi
        - gecontroleerd_madi
        - verzonden_madi
        - bezig_gka
      transitions:
        opgevoerd_madi: { from: [bezig_madi], to: compleet_madi }
        goedkeuren_madi: { from: [compleet_madi], to: gecontroleerd_madi }
        afkeuren_madi: { from: [compleet_madi, gecontroleerd_madi], to: bezig_madi }
        verzenden_madi: { from: [gecontroleerd_madi], to: verzonden_madi }
        gestart_gka: { from: [verzonden_madi], to: bezig_gka }
