version: '3.2'
services:
  database_dev:
    image: postgres:9.5.11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: schuldhulp
      POSTGRES_DB: schuldhulp
  web_dev:
    build:
        context: .
        dockerfile: Dockerfile-dev
    restart: always
    volumes:
      - type: bind
        source: ./config
        target: /srv/app/config
      - type: bind
        source: ./public
        target: /srv/app/public
      - type: bind
        source: ./src
        target: /srv/app/src
      - type: bind
        source: ./templates
        target: /srv/app/templates
    ports:
      - "80:80"
    links:
      - database_dev
    environment:
      - APP_ENV=dev
      - APP_SECRET=secret
      - DATABASE_URL=pgsql://schuldhulp:insecure@database_dev:5432/schuldhulp
      - SWIFT_AUTH_URL=
      - SWIFT_REGION=
      - SWIFT_USER_NAME=
      - SWIFT_USER_DOMAIN_ID=
      - SWIFT_USER_PASSWORD=
      - SWIFT_PROJECT_ID=
      - SWIFT_CONTAINER_PREFIX=
      - SWIFT_TEMP_URL_KEY=
      - SWIFT_EXTERNAL_DOMAIN=

