version: '3.0'
services:
  database:
    image: postgres:9.5.11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: schuldhulp
      POSTGRES_DB: schuldhulp
  web:
    build:
        context: .
        dockerfile: Dockerfile
    links:
      - database
    environment:
      - APP_ENV=production
      - APP_SECRET=secret
      - DATABASE_URL=pgsql://schuldhulp:insecure@database:5432/schuldhulp
