# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    url: 'null'
    transport: 'smtp'
    host: 'mailhog_dev'
    username: 'null'
    password: 'null'
    port: '1025'

    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
