parameters:
    locale: 'nl'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    GemeenteAmsterdam\FixxxSchuldhulp\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    GemeenteAmsterdam\FixxxSchuldhulp\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    GemeenteAmsterdam\FixxxSchuldhulp\EventListener\GebruikerPasswordSubscriber:
        arguments:
            - '@security.user_password_encoder.generic'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
